### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
Reliefs -> relieves

**Comment by maelle** [comment]
But now I am doubting myself 🤔

**Comment by EdwinTh** [comment]
Checked it, you are right. reliefs is the plural of the non relief, relieves is the verb. Thanks!

**Comment by maelle** [comment]
Ah ok, cool! If only all plurals worked similarly... E.g. thief/thieves. :grin:

**Pull request merged**
